refactor: move check pro rocks inside read-config

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -23,6 +23,19 @@ jobs:
         id: read-ci-config
         uses: canonical/rocks-template-actions/actions/read-ci-config@v1
 
+      - name: Check for Pro rocks in matrix
+        run: |
+          matrix='${{ steps.read-ci-config.outputs.build-matrix }}'
+          visibility='${{ github.event.repository.visibility }}'
+
+          # Use jq to check if any 'pro-services' array is non-empty
+          has_pro=$(echo "$matrix" | jq '[.include[] | select(.["pro-services"] != null and (.["pro-services"] | length > 0))] | length')
+
+          if [ "$has_pro" -gt 0 ] && [ "$visibility" = 'public' ]; then
+            echo "::error::This repository is public but defines one or more pro-enabled rocks."
+            exit 1
+          fi
+
   get-runners:
     runs-on: ubuntu-latest
     outputs:
@@ -36,29 +49,12 @@ jobs:
             echo 'arch-map={"amd64":["ubuntu-24.04"],"arm64":["ubuntu-24.04-arm"]}' >> $GITHUB_OUTPUT
           fi
 
-  check-pro-rocks:
-    needs: read-config
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check for Pro rocks in matrix
-        run: |
-          matrix='${{ needs.read-config.outputs.build-matrix }}'
-          visibility='${{ github.event.repository.visibility }}'
-
-          # Use jq to check if any 'pro-services' array is non-empty
-          has_pro=$(echo "$matrix" | jq '[.include[] | select(.["pro-services"] != null and (.["pro-services"] | length > 0))] | length')
-
-          if [ "$has_pro" -gt 0 ] && [ "$visibility" = 'public' ]; then
-            echo "::error::This repository is public but defines one or more pro-enabled rocks."
-            exit 1
-          fi
-
   # Why do we need this duplicate job and reusable Build-Rock workflow?
   # - the Build-Rock wf may need an an environment setup that relies on an internal action
   #   - to call an internal action, the repo must also be internal/private
   #     - but the OCI Factory is not internal/private, so that internal action cannot be called from there
   build-internal:
-    needs: [get-runners, read-config, check-pro-rocks]
+    needs: [get-runners, read-config]
     if: github.event.repository.visibility != 'public'
     strategy:
       fail-fast: true
@@ -75,7 +71,7 @@ jobs:
       source-github-token: ${{ secrets.REPO_CLONER_TOKEN }}
 
   build:
-    needs: [get-runners, read-config, check-pro-rocks]
+    needs: [get-runners, read-config]
     if: github.event.repository.visibility == 'public'
     strategy:
       matrix: ${{ fromJSON(needs.read-config.outputs.build-matrix) }}
